import express from "express";
import requireAuth from "../middleware/requireAuth.js";
import requireRole from "../middleware/requireRole.js";
import { getActivityLog } from "../services/activityLogService.js";

const router = express.Router();

// RBAC rationale: "Riwayat Aktivitas" is Admin-only in
// src/utils/navigation.js's menuByRole — requireRole("Admin") here is the
// real security boundary, not the frontend's cosmetic menu gating.
router.get("/", requireAuth, requireRole("Admin"), async (req, res, next) => {
  try {
    const activityLog = await getActivityLog();
    return res.status(200).json(activityLog);
  } catch (error) {
    return next(error);
  }
});

// No POST route is exposed here — catatAktivitas is an internal
// side-effect-only function called by permintaan/keputusan/kota/stok
// mutations, never directly by the client. This is the literal meaning of
// LOGIC-03: log entries are generated BY mutations, not submitted
// independently. A client cannot fabricate history.

export default router;
