import express from "express";
import requireAuth from "../middleware/requireAuth.js";
import { getNotifikasi, tandaiDibaca, tandaiSemuaDibaca } from "../services/notifikasiService.js";

const router = express.Router();

// Notifikasi is a cross-cutting Layout.jsx feature, not Admin-gated in
// src/utils/navigation.js — every authenticated role reads and marks its
// own notifications. No requireRole on any route here.

router.get("/", requireAuth, async (req, res, next) => {
  try {
    const notifikasi = await getNotifikasi();
    return res.status(200).json(notifikasi);
  } catch (error) {
    return next(error);
  }
});

router.put("/:id/baca", requireAuth, async (req, res, next) => {
  try {
    const notifikasi = await tandaiDibaca(req.params.id);
    return res.status(200).json(notifikasi);
  } catch (error) {
    return next(error);
  }
});

router.put("/baca-semua", requireAuth, async (req, res, next) => {
  try {
    const notifikasi = await tandaiSemuaDibaca();
    return res.status(200).json(notifikasi);
  } catch (error) {
    return next(error);
  }
});

// No POST route is exposed here — tambahNotifikasi is an internal
// side-effect-only function called by permintaanService/keputusanService
// mutations, never directly by the client (LOGIC-03: notifications are
// generated BY mutations, not submitted independently).

export default router;
